### ISSUE TITLE
"node" command not found

### ISSUE THREAD

**Issue by Levis44** [luasenvy/ulauncher-node#5]
![image](https://github.com/luasenvy/ulauncher-node/assets/62621313/c9b7755f-be68-417a-9aa2-1e02c03f5205)

Just installed this extension, but does not work

**Comment by luasenvy** [comment]
sorry for late.

this extension is required `nodejs`.

please check `node -v` command is working.

this extension is detect `nodejs` from:
`which node`
`/snap/bin/node`
`/usr/local/bin/node`

solution:
if nodejs is not installed in your system.

i recommend install via [snapcraft](https://snapcraft.io/)

`sudo snap install node --classic`

or

if you don't want register in `PATH`.
make symlink to `/snap/bin/node` or `/usr/local/bin/node`.

hope this helps
